### ISSUE TITLE
Question: How much effort would this be to port to Windows?

### ISSUE THREAD

**Issue by thornley-permaconn** [dragonlock2/stbridge#2]
Having linux/macos support is great, but my use case is partly to service existing manufacturing environments that are using Windows.

I noticed that the bridge wrapper recompiles the ST official usb driver from source, however on windows they do release STLinkUSBDriver.dll (in [STSW-LINK007](https://www.st.com/en/development-tools/stsw-link007.html)) as the low level library. It seems like it should work ok with the ST bridge cpp/h and your bridge wrapper based on boost:python.

Do you have any plans to port to windows? If not, do you foresee any major difficulties with porting it across to windows?

**Comment by dragonlock2** [comment]
No current plans to port to Windows. The only issue I see porting it would be getting the development environment set up. STLinkUSBDriver.dll shouldn't be necessary with this project since we use an alternative purely libusb based driver. It would be necessary with the original bridge API source code from ST.

**Comment by dragonlock2** [comment]
Done! I ended up having to learn how to do this for my new project https://github.com/dragonlock2/JABI so applied that work here too. It's now locally pip installable so it's far easier to manage. Check the README for more details.

I probably won't be doing further work on this since I'll be dedicating my time towards JABI which is more properly open-source.

**Comment by thornley-permaconn** [comment]
Awesome, thanks I ended up working with a heavily hacked fork of the code for Windows... I will check out and adopt the official approach, many thanks @dragonlock2
